### PR TITLE
Support github releases

### PR DESCRIPTION
**Pull request by omicron-o**
As mentioned in #199, this pull request adds an extra site handler `GitHubReleases` which handles using github releases as source for addons. The way it recognizes that a release should be used instead of the default branch is by detecting github urls that end in /releases. For example:

```
https://github.com/WeakAuras/WeakAuras2/releases
https://github.com/BigWigsMods/BigWigs/releases
```

I opted for this because that seemed to be the only reasonable way to distinguish between different github sources. Appending extra data after the URL seems to already be in use and would require more changes. This url scheme can also be easily extended to `/tags` (some addon repos create tags but not releases).

I opted for creating a second class for two reasons:

 * The GitHub class already receives special treatment for unzipping the files (in the addon manager code).
 * The logic for finding the release zips and versions is nicely separated

It has one downside though: the `GitHubReleases` has its own session and thus uses a separate cookiejar. I don't think this is a significant issue but I'm open to change this if you have suggestions. Both the `GitHub` and `GitHubReleases` class now override the `AbstractSite.handles` method instead of using the default implementation, I'm open to changing that if you have suggestions there too.

Edit: I just edited my addons.txt and went over all addons, converting them to use the author's github releases when available. Roughly half my addons.txt now uses github releases.

### CODE REVIEW

**Comment by omicron-o** [comment]
Updating my addons.txt and having more than a few test addons in it has revealed a flaw. Github rate limits the requests to its API if you are not authenticated. I'm not sure exactly what the rate limit is, but I've changed the manager to not use thread pools as a test and added a 5 second sleep in between each addon and I still triggered the rate limit. Will look into it more and report back when I find some time.

File: updater/site/github_release.py [hunk 1]
```diff
@@ -0,0 +1,61 @@
...
+    _URLS = ['https://www.github.com/', 'https://github.com/']
+
+    session = requests.session()
+
+    def __init__(self, url: str):
+        super().__init__(url, GameVersion.agnostic)
+
+    @classmethod
+    def handles(cls, url: str) -> bool:
+        v = bool(re.match('^https://(www.)?github.com/[^/]+/[^/]+/releases/?$', url))
```
Comment (grrttedwards) [inline updater/site/github_release.py:20]: redundant, but unimportant. I'll fix this before publishing a new version

**Comment by grrttedwards** [comment]
I think it looks pretty good! The build process expired for this repo because it started failing consistently when Curse changed something up :( 
The github rate limit must also apply to the other kind of github site... never hit it before. I'll accept this and try to get around to fixing up the build and release process. Thanks! In the meantime, you could pull master once this is in there.

File: updater/site/github_release.py [hunk 2]
```diff
@@ -0,0 +1,61 @@
...
+        return bool(re.match('^https://(www.)?github.com/[^/]+/[^/]+/releases/?$', url))
```
Comment (grrttedwards) [inline updater/site/github_release.py:21]: This works great. Only because you asked for a bit of feedback, I think if I were to write this, I'd have just made it something like:
```suggestion
        return any(url.startswith(allowed_url) and url.endswith('/releases') for allowed_url in _URLS)
```

File: updater/site/site_handler.py [hunk 3]
```diff
@@ -23,6 +24,8 @@ def get_handler(url: str, game_version: GameVersion,
         return WoWInterface(url, game_version)
     elif GitHub.handles(url):
         return GitHub(url)
+    elif GitHubRelease.handles(url):
+        return GitHubRelease(url)
```
Comment (grrttedwards) [inline updater/site/site_handler.py:28]: Also a nitpick, could have dodged changing `GitHub`'s handler if we just check the release style first
```suggestion
    elif GitHubRelease.handles(url):
        return GitHubRelease(url)
    elif GitHub.handles(url):
        return GitHub(url)
```

**Comment by omicron-o** [comment]
I saw there is another PR which has some configuration module changes (#86). Is this being considered too or has it aged sufficiently that it's no longer a good fit for short term merging? I'm only asking because I would consider adding the ability to configure a github API key. You can very easily make personal API keys that have limited permissions to bypass the 60/hour limit. 

Further, do you want me to pull these suggestions into my branch and flesh out this request or should I just wait?

File: updater/site/github_release.py (hunk 1 above)
Comment (omicron-o) [reply updater/site/github_release.py:20]: Oh you are absolutely right. I missed this when cleaning up the code.

File: updater/site/site_handler.py (hunk 3 above)
Comment (omicron-o) [reply updater/site/site_handler.py:28]: I've been thinking a bit more about this and while it is indeed true that this would allow the default implementation to remain for `GitHub.handles`, it would also make `GitHub.handles` incorrectly report `True` for urls that it can not handle correctly. When you append `/releases` to the url the code in `GitHub.get_addon_name` will misbehave and cause the addon download to no longer work.

**Comment by omicron-o** [comment]
I have expanded on the pull request by also adding support for a personal access token. This will increase the API request limit from a low 60 requests per hour (at 2 requests per addon, this is hit rather quickly) to a much more reasonable 5000 requests per some unit of time (presumably also an hour, I didn't verify).

To create a personal access token you can look at https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token#creating-a-fine-grained-personal-access-token. Personally I have made a fine-grained token without any permissions.

I tried to be reasonable about the type hints, but let me know if the `dict[str, dict[str, str]]` needs to change.

This commit also removes the redundant expression in `GitHubRelease.handles` but I have not yet touched on the other suggestions since they seemed less important.

**Comment by grrttedwards** [comment]
Again, looks great. Let me try to fix up a build process for this so we can validate the changes automatically. Would you mind adding tests for the additional behavior? It saves me headaches in a year when someone suggests we need a modification :)

File: updater/site/site_handler.py (hunk 3 above)
Comment (grrttedwards) [reply updater/site/site_handler.py]: Sure enough, it was "broken" before by that definition. Your reasoning is fine.

**Comment by grrttedwards** [comment]
The build is running again, but it's probably going to be impossible to run the Curse integration tests on the github runners.... Cloudflare definitely blocks the runner CIDR since there's so much potential for spam from it. May just disable them on CI....

**Comment by omicron-o** [comment]
I'll take a look at adding tests over the next few days. I have not yet looked at your tests but it seems you are using the standard unittest so I should be able to get that working.

**Comment by omicron-o** [comment]
I've added the tests. I believe it should be possible to use the automatically generated GITHUB_TOKEN in github actions. If it is exported to the environment before the tests are executed, then the tests will use that token to authenticate.

I'm not 100% sure if the automatically generated token can be used for general API requests to other repositories, but I think it should work since those are all API calls that don't require any specific permission.

All relevant tests are passing, but some others still fail because I did not merge master yet. Do you have any preference towards merging in master or rebasing onto master in a feature branch? This should be the final change for this pull request unless I missed something.

File: test/site/test_github_release.py [hunk 4]
```diff
@@ -0,0 +1,38 @@
...
+import os
+
+from updater.site.github_release import GitHubRelease
+
+
+class TestGithubRelease(unittest.TestCase):
+    def setUp(self):
+        self.url = "https://github.com/smp4903/FiveSecondRule/releases"
+        credentials = None
+        if token := os.environ.get("GITHUB_TOKEN"):
```
Comment (grrttedwards) [inline test/site/test_github_release.py:11]: Very nice, thanks for that

**Comment by grrttedwards** [comment]
I thought that `str.removeprefix()` looked a little funny, I didn't recognize it 😅 

I haven't used a new enough version of python with it, this proj works with python 3.7+

```
AttributeError: 'str' object has no attribute 'removeprefix'
```

**Comment by omicron-o** [comment]
Yeah I was just looking into it. I only have 3.10 on my system so I didn't catch it during testing. I'll push a fix in a minute.

**Comment by grrttedwards** [comment]
I'm trying to remember how to operate this project, so no worries, I got it

**Comment by grrttedwards** [comment]
Just curse tests failing -- that's never going to work, so lgtm! ✅
